### ISSUE TITLE
Accès impossible page "Mon Compte"

### ISSUE THREAD

**Issue by vincentux** [duniter/cesium_ynh#1]
Impossible d’accéder à la page "Mon Compte", celle ci tourne en boucle.
Sur navigateur Firefox 47.

**Comment by M5oul** [comment]
Je ne rencontre pas ce problème sur mon environnement de développement et sur une carte ARM.

**Comment by vincentux** [comment]
Quand j'actualise ma page : 

![bug_cesium](https://cloud.githubusercontent.com/assets/11737560/16042160/b6d3be68-3239-11e6-82b7-955a7e97bc36.png)

**Comment by M5oul** [comment]
Same than https://github.com/duniter/cesium_ynh/issues/2.
